import { ComponentType } from "../models/enums/ComponentType";
import { CreateComponentRequest } from "../api/Component/models/CreateComponentRequest";

export const componentDefaults: Record<ComponentType, CreateComponentRequest> =
  {
    [ComponentType.Text]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 35,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Text,
      style: "textColor:#000000",
    },
    [ComponentType.Image]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 212,
      height: 200,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Image,
      content: `/assets/images/placeholders/image-component-placeholder.png`,
    },
    [ComponentType.Video]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 358,
      height: 200,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Video,
      content: "Insert url to see video",
    },
    [ComponentType.Arrow]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 225,
      height: 70,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Arrow,
      style: "fillColor:#64b5f6",
    },
    [ComponentType.Circle]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Circle,
      style: "fillContent:#ba68c8",
    },
    [ComponentType.Cross]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Cross,
      style: "fillColor:#7e57c2",
    },
    [ComponentType.Diamond]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Diamond,
      style: "fillColor:#4fc3f7",
    },
    [ComponentType.Heart]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Heart,
      style: "fillColor:#e91e63",
    },
    [ComponentType.Message]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 225,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Message,
      style: "fillColor:#AED581",
    },
    [ComponentType.Plus]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Plus,
      style: "fillColor:#EF5350",
    },
    [ComponentType.Polygon]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Polygon,
      style: "fillColor:#81c784,sides:6",
    },
    [ComponentType.Rectangle]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 225,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Rectangle,
      style: "fillColor:#90caf9",
    },
    [ComponentType.Square]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Square,
      style: "fillColor:#DFB6FD",
    },
    [ComponentType.Star]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Star,
      style: "fillColor:#ffd54f",
    },
    [ComponentType.Triangle]: {
      worksheetId: 0,
      x: 0,
      y: 0,
      width: 150,
      height: 150,
      rotation: 0,
      zIndex: 1,
      type: ComponentType.Triangle,
      style: "fillColor:#a1887f",
    },
  };
